import { PrimeReactProvider } from 'primereact/api';
import 'primereact/resources/themes/lara-light-blue/theme.css';

export const metadata = {
 title: 'Next.js',
 description: 'Generated by Next.js',
};

export default function RootLayout({
 children,
}: {
 children: React.ReactNode;
}) {
 return (
  <html lang="en">
   <body>
    <PrimeReactProvider>{children}</PrimeReactProvider>
   </body>
  </html>
 );
}
